# -*- coding: utf-8 -*-
"""calculadora3.0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LdtS9vj2oBLWWvui5YsfgKmmoeWFTf7R
"""

his = []

while True:

    print('====='*10)
    inicio = int(input('''
    Digite 1 para usar a calculadora: 

    Digite 2 para ver o historico:

    Digite 3 convertor de denheiro:

    Digite 4 para sair:
    '''))
    print('====='*10)

    b = '\\'
    his.append(b)

    if inicio == 1:
        n1 = int(input('Digite um numero: '))
        his.append(n1)
        
        funcoes = input('''
        Digite + para soma: 
        Digite - para subitrair: 
        Digite * para mutiplicar:
        Digite / para dividir: 
                ''')

        his.append(funcoes)
        n2 = int(input('Digite um numero: '))
        his.append(n2)
        volta = input('Aperte Enter para mostra o resultado: ')
        if volta == '':
            pass

        recebe = '='
        his.append(recebe)

        if funcoes == '+':
            resultado = n1 + n2
            print('x-x-x-x-x'*10)
            a = print(f'''
            
            {n1} {funcoes} {n2} = {resultado}
            
            ''')
            print('x-x-x-x-x'*10)

        elif funcoes == '-':
            resultado = n1 - n2
            print('x-x-x-x-x'*10)
            a = print(f'''
            
            {n1} {funcoes} {n2} = {resultado}
            
            ''')
            print('x-x-x-x-x'*10)

        elif funcoes == '*':
            resultado = n1 * n2
            print('x-x-x-x-x'*10)
            a = print(f'''
            
            {n1} {funcoes} {n2} = {resultado}
            
            ''')
            print('x-x-x-x-x'*10)

        elif funcoes == '/':
            resultado = n1 / n2
            print('x-x-x-x-x'*10)
            a =  print(f'''
            
            {n1} {funcoes} {n2} = {resultado}
            
            ''')
            print('x-x-x-x-x'*10)
        
            his.append(resultado)
        
        

    elif inicio == 2:
        print(his)

    elif inicio == 3:
        print('====='*10)
        escolha =  int(input('''

        Digite 1 para converte Dolar em Reais :
        Digite 2 para converte Resis em Dolar : 

        Digite 3 para converte Euros em Reais :
        Digite 4 para converte Reais em Euros :

        Digite 5 para converte Libra em Reais :
        Digite 6 para converte Reais em Libra :


        '''))
        print('====='*10)

        if escolha == 1:
            dolar = float(input('Digite o valor em Dolar: '))
            solucao = 4.98 * dolar
            print('x-x-x-x-x'*10)
            print(f'''
            
            {solucao:.2f} Reais
            
            ''')
            print('x-x-x-x-x'*10)

        elif escolha == 2 :
            reais = float(input('Digite o valor e Reais: '))
            solucao = reais / 4.98
            print('x-x-x-x-x'*10)
            print(f'''
            
            {solucao:.2f} Dolares
            
            ''')
            print('x-x-x-x-x'*10)

        elif escolha == 3:
            euro = float(input('Digite o valor em Euros: '))
            solucao = 5.45 * euro
            print('x-x-x-x-x'*10)
            print(f'''
            
            {solucao:.2f} reais: 
            
            ''')
            print('x-x-x-x-x'*10)

        elif escolha == 4:
            reais = float(input('Digite o valor em Reais: '))
            solucao =  reais / 5.45
            print('x-x-x-x-x'*10)
            print(f'''
            
            {solucao:.2f} Euros
            
            ''')
            print('x-x-x-x-x'*10)

        elif escolha == 5:
            libra = float(input('Digite o valor em Libra: '))
            solucao = 6.19 * libra
            print('x-x-x-x-x'*10)
            print(f'''

            {solucao:.2f} reais 
            
            ''')
            print('x-x-x-x-x'*10)

        elif escolha == 6:
            reais = float(input('Digite o valor em reais: '))
            solucao = reais /6.19
            print('x-x-x-x-x'*10)
            print(f'''
            
            {solucao:.2f} Libra
            
            ''')
            print('x-x-x-x-x'*10)

        else:
            print('Digite um numero valido!!!')

    elif inicio == 4:
        break

    else:
        print('''
        
        Digite um numero valido!!!
        
        
        
        ''')